services:
  # PostgreSQL база данных
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comeback_admin
      POSTGRES_USER: comeback_user
      POSTGRES_PASSWORD: comeback_password_2025
    restart: unless-stopped
    networks:
      - comeback_network

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - comeback_network

  # Django приложение
  web:
    build: .
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    environment:
      - DEBUG=False
      - SECRET_KEY=your-super-secret-key-change-in-production-2025
      - ALLOWED_HOSTS=89.39.95.190,localhost,127.0.0.1
      - DATABASE_URL=postgresql://comeback_user:comeback_password_2025@db:5432/comeback_admin
      - REDIS_URL=redis://redis:6379/0
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - comeback_network
    command: >
      sh -c "python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 comeback_admin.wsgi:application"       

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/var/www/static
      - media_files:/var/www/media
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - comeback_network

volumes:
  postgres_data:
  media_files:
  static_files:

networks:
  comeback_network:
    driver: bridge
