# Generated by Django 5.2.4 on 2025-08-18 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='6-значный OTP код', max_length=6, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма оплаты', max_digits=10)),
                ('quantity', models.IntegerField(default=1, help_text='Количество чеков/активаций')),
                ('currency', models.CharField(default='UZS', help_text='Валюта', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('used', 'Использован'), ('expired', 'Истек')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания')),
                ('used_at', models.DateTimeField(blank=True, help_text='Время использования', null=True)),
                ('device_id', models.CharField(blank=True, help_text='ID устройства, использовавшего код', max_length=255, null=True)),
                ('firebase_key', models.CharField(blank=True, help_text='Ключ в Firebase', max_length=255, null=True)),
                ('created_by', models.ForeignKey(help_text='Кассир, создавший код', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP код',
                'verbose_name_plural': 'OTP коды',
                'ordering': ['-created_at'],
            },
        ),
    ]
