# Generated by Django 4.2.7 on 2025-08-18 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, help_text='Цена в сумах за подписку', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена подписки (сум)')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Количество минут доступа к AR контенту', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Длительность подписки (минуты)')),
                ('currency', models.CharField(default='UZS', help_text='Код валюты (UZS, USD, EUR и т.д.)', max_length=10, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить систему подписки', verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.CharField(blank=True, max_length=150, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Настройки подписки',
                'verbose_name_plural': 'Настройки подписки',
            },
        ),
    ]
