# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=True, help_text='Разрешить оплату картой / интернет-эквайринг в приложении', verbose_name='Интернет-оплата (эквайринг)'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='otp_enabled',
            field=models.BooleanField(default=True, help_text='Разрешить оплату по OTP-кодам (наличные) в приложении', verbose_name='OTP (наличные коды)'),
        ),
    ]
