# Generated by Django 4.2.7 on 2025-08-18 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество билетов')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
            ],
            options={
                'verbose_name': 'Наличный платеж',
                'verbose_name_plural': 'Наличные платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activation_code', models.CharField(max_length=64, unique=True, verbose_name='Код активации')),
                ('qr_data', models.TextField(verbose_name='Данные QR кода')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность (минуты)')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('used', 'Использован'), ('expired', 'Истек')], default='active', max_length=20, verbose_name='Статус')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID устройства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='cashier.cashpayment')),
            ],
            options={
                'verbose_name': 'Код активации',
                'verbose_name_plural': 'Коды активации',
                'ordering': ['-created_at'],
            },
        ),
    ]
