from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    MeView,
    DashboardStatsView,
    VideoListView,
    VideoCreateView,
    VideoDetailView,
    VideoDeleteView,
    PaymentListView,
    OTPListView,
    OTPCreateView,
    OTPCashPaymentView,
    OTPDetailView,
    SubscriptionSettingsView,
    StatisticsView,
    PaymentGatewayDashboardView,
    PaymentGatewayTransactionDetailView,
    PaymentGatewayTestPaymentView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/me/', MeView.as_view()),
    path('dashboard/stats/', DashboardStatsView.as_view()),
    path('videos/', VideoListView.as_view()),
    path('videos/create/', VideoCreateView.as_view()),
    path('videos/<str:video_id>/', VideoDetailView.as_view()),
    path('videos/<str:video_id>/delete/', VideoDeleteView.as_view()),
    path('payments/', PaymentListView.as_view()),
    path('otp/', OTPListView.as_view()),
    path('otp/create/', OTPCreateView.as_view()),
    path('otp/cash-payment/', OTPCashPaymentView.as_view()),
    path('otp/<uuid:otp_id>/', OTPDetailView.as_view()),
    path('subscription/settings/', SubscriptionSettingsView.as_view()),
    path('statistics/', StatisticsView.as_view()),
    path('payment-gateway/', PaymentGatewayDashboardView.as_view()),
    path('payment-gateway/transaction/<str:order_id>/', PaymentGatewayTransactionDetailView.as_view()),
    path('payment-gateway/test-payment/', PaymentGatewayTestPaymentView.as_view()),
]
