# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID заказа')),
                ('amount', models.IntegerField(verbose_name='Сумма (в суммах)')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Успешно'), ('failed', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('unity_user_id', models.CharField(blank=True, max_length=100, verbose_name='ID пользователя Unity')),
                ('unity_session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии Unity')),
                ('merchant_id', models.CharField(default='552170', max_length=50, verbose_name='Merchant ID')),
                ('salt', models.CharField(max_length=100, verbose_name='Соль')),
                ('signature', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция платежа',
                'verbose_name_plural': 'Транзакции платежей',
                'ordering': ['-created_at'],
                'db_table': 'payment_gateway_transactions',
            },
        ),
        migrations.CreateModel(
            name='UnityPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID сессии')),
                ('unity_user_id', models.CharField(max_length=100, verbose_name='ID пользователя Unity')),
                ('amount', models.IntegerField(verbose_name='Сумма (в суммах)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Сессия платежа Unity',
                'verbose_name_plural': 'Сессии платежей Unity',
                'ordering': ['-created_at'],
                'db_table': 'payment_gateway_unity_sessions',
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(max_length=20, verbose_name='Тип callback')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payment_gateway.paymenttransaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': "Callback платежа",
                'verbose_name_plural': "Callback'ы платежей",
                'ordering': ['-created_at'],
                'db_table': 'payment_gateway_callbacks',
            },
        ),
    ]
