# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('freedom', 'FreedomPay'), ('milliy', 'Milliy Ecom')], default='freedom', max_length=20, verbose_name='Платёжный шлюз'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='milliy_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Milliy Transaction ID'),
        ),
    ]
