# Generated by Django 4.2.7 on 2025-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_payments', models.IntegerField(default=0, verbose_name='Всего платежей')),
                ('successful_payments', models.IntegerField(default=0, verbose_name='Успешных платежей')),
                ('failed_payments', models.IntegerField(default=0, verbose_name='Неуспешных платежей')),
                ('pending_payments', models.IntegerField(default=0, verbose_name='Ожидающих платежей')),
                ('total_revenue', models.IntegerField(default=0, verbose_name='Общий доход (сумм)')),
                ('total_subscriptions', models.IntegerField(default=0, verbose_name='Всего подписок')),
                ('active_subscriptions', models.IntegerField(default=0, verbose_name='Активных подписок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID заказа')),
                ('amount', models.IntegerField(verbose_name='Сумма (в суммах)')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Успешно'), ('failed', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('user_id', models.CharField(blank=True, max_length=100, verbose_name='ID пользователя')),
                ('user_info', models.JSONField(blank=True, default=dict, verbose_name='Информация о пользователе')),
                ('subscription_duration', models.IntegerField(default=15, verbose_name='Длительность подписки (мин)')),
            ],
            options={
                'verbose_name': 'Запись о платеже',
                'verbose_name_plural': 'Записи о платежах',
                'ordering': ['-created_at'],
            },
        ),
    ]
